apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: java-project-gateway
  labels:
spec:
  hostname: java-project-gateway
  subdomain: default-subdomain
  containers:
  - image: dworza/java-project-gateway:latest
    name: java-project-gateway
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image:  dworza/time-provider:latest
    command:
    name: busybox


